services:
  frontend_prod:
    container_name: frontend_prod
    build: .
    volumes:
      - .:/var/www/demo
    ports:
      - "4000:3000"
      
  pocketbase_prod:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_prod
    restart: unless-stopped
    ports:
      - "8090:8090"
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5