name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TARGET_DIR: ${{ secrets.SSH_FOLDER }}  # You can set this to any directory, and make it dynamic as needed.

    steps:
      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd $TARGET_DIR
            git pull
            chmod u+x ./bin/extend.sh
            ./bin/extend.sh
            cd storefront
            git pull
            bun install
            bun run build
            bun x pm2 restart ecosystem.config.cjs
