name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: admin.pocketstore.io
          username: "root"  
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/demo
            git pull
            chmod u+x ./bin/extend.sh
            ./bin/extend.sh
            cd storefront
            git pull
            bun install
            bun run build
            bun x pm2 restart ecosystem.config.cjs